### ISSUE TITLE
Find id of the notification

### ISSUE THREAD

**Issue by psohm** [MeTaLiKiD/Bootstrap4NotificationsSample#1]
in the markAsRead event, how do you know the id of the event ?

Merci ! :)

**Comment by MeTaLiKiD** [comment]
Oh god, that's not my best best code, that's old.

```
markAsRead: function (event, elem) {

      /* ... */

     /* I'm using the parent off the little cross (fa-times) to remote it */
      elem.parent('.dropdown-notification').remove();

     /* You can get the ID by doing */
      var notificationId = elem.parent('.dropdown-notification').attr('id');

     /* ... */

    },
```

But honestly, it will be better to have the ID of the notification on an attribut off the remove button, like this :

```
      <div class="notification-read" data-notification-id="1">
        <i class="fa fa-times" aria-hidden="true"></i>
      </div>
```

and then :

```
 var notificationId = elem.attr('data-notification-id');
OR
 var notificationId = elem.data('notification-id');
```

**Comment by psohm** [comment]
tks
I do not use that component as is
but it's a nice begin

btw on peut continuer en francais
je n'ai pas compris à quoi sert markAsReadDesktop

**Comment by MeTaLiKiD** [comment]
**markAsReadDesktop** :
Ce composant, je l'ai extrait d'un dashboard complet.
Il y avait une page pour voir les notifications, comme sur GitHub.
C'était le JS pour marquer une notification comme lue dans sur cette page.

--

Je te conseil de jeter un œil à mon autre projet [bboard](https://metalikid.github.io/bboard/), j'y ai amélioré le système de notification.

J'avais comme idée de faire un Dashboard avec tous pleins de composants, mais je n'ai pas pris le temps de continuer.

Et surtout que j'en ai trouvé un très sympa, [AdminLTE](https://github.com/ColorlibHQ/AdminLTE)

**Comment by psohm** [comment]
je te remercie c'est pas spécialement évident de trouver ce type de composant séparé.
et également un minimum lisible
